### ISSUE TITLE
Use Vulkava without the built-in player queue

### ISSUE THREAD

**Issue by sawa-ko** [davidffa/Vulkava#11]
Currently I see that the `play` method of the `Player` class checks the queue of the music player and in case there are no more songs it throws an error.

I don't want to use the built-in queue because I want to use my own queue but I don't see an option to disable the already built-in queue.

**Comment by davidffa** [comment]
How would you provide a track to be played with your custom queue? Directly to Player#play() method ?

**Comment by kaname-png** [comment]
It would be these steps:
1. Use my queue class.
2. Get the following song.
3. Pass the Track in the .play() method.
4. At the end of the song use my queue class method to clear the preproduction queue.

If there was a `disableBuiltInQueue` option, this could be achieved, so as not to depend on the Vulkava playback queue.

**Comment by davidffa** [comment]
What do you think about creating a AbstractQueue class on vulkava and your custom queue class extend that class which has the method `poll` which Player#play() will call.

Something like this:
```ts
// AbstractQueue.ts
export abstract class AbstractQueue {
  abstract get duration(): number;

  abstract poll(): Track | UnresolvedTrack | null;
}
```
```js
// YourQueue.js or ts
class YourQueue extends AbstractQueue {
  get duration() {
    return <queue duration here>;
  }

 poll() {
    return <the next track in the queue>;
  }
}
```

and you'll set the custom queue with
`<vulkava>.createPlayer({ ......, customQueue: new YourQueue() })`
then the Player#play() method will call YourQueue#poll() method to get the next track

**Comment by kaname-png** [comment]
I like how it looks, thanks.
