### ISSUE TITLE
Lib fails to function when processing certain links

### ISSUE THREAD

**Issue by Seek0999** [davidffa/Vulkava#15]
When playing certain links e.g. Spotify links, the lib fails to function completely for some reason. I'm not sure why this happens but i get a range of errors when attempting to queue a spotify song.

Error 1:
```
vulkava\lib\Player.js:279
            track: this.current.encodedTrack,

TypeError: Cannot read properties of undefined (reading 'encodedTrack')
```

Error 2:
```
(Track Exception) TypeError: Cannot read properties of undefined (reading 'setRequester')
```
Cause: I've narrowed it down to it only ocurring when coming in contact with an unresolved track,
The error in the code is caused by the lib originating from:
``` 
vulkava\lib\UnresolvedTrack.js:35
```

**Vulkava Version: 1.5.6**

**Comment by davidffa** [comment]
Fixed by https://github.com/davidffa/Vulkava/commit/12fe44ab358d7ea2e465d6b577637fe5741dea6c
