### ISSUE TITLE
Question about version

### ISSUE THREAD

**Issue by http-ph** [davidffa/Vulkava#19]
What version of lavalink do you recommend using with the latest vulkava release? Thanks in advance.

**Comment by subscrip** [comment]
hi, you can use the modified version that is on the wiki!

**Comment by http-ph** [comment]
> Hi, you can use the modified version that is on the wiki!

right, but the mod version is not a little outdated? or it's not a problem?

**Comment by http-ph** [comment]
Perfect, tysm! You did a good job in Vulkava. It's pretty good.
