### ISSUE TITLE
[Suggestion] Add support to youtube music URL

### ISSUE THREAD

**Issue by phgrandi** [davidffa/Vulkava#22]
When the user tries to load a music from Youtube Music that has "music." in the URL, it returns an error, but just removing the "music." it plays.

So, I'm suggesting to add it in the URL regex to filter it as well.

**Comment by davidffa** [comment]
If you provide an URL to the Vulkava#search method, it directly sends a request to the lavalink with that URL, so probably its a Lavalink/Lavaplayer issue, not a Vulkava issue.
