### ISSUE TITLE
VC

### ISSUE THREAD

**Issue by Kugyan** [davidffa/Vulkava#25]
O bot sai do vc depois de entrar.
Discord.js: **v14.14.1**
Vulkava: **v1.6.3**

**Comment by joaopedrosilvestrini** [comment]
Olá @Kugyan tudo bem?

Por algum acaso, você está usando o evento raw?

**Comment by Kugyan** [comment]
Sim, com sharding: `client.on('raw', (packet) => client.vulkava.handleVoiceUpdate(packet));`.

**Comment by joaopedrosilvestrini** [comment]
Consegue me mostrar seu comando de tocar e a configuração do seu vulkava?

**Comment by Kugyan** [comment]
index.js: `client.vulkava = new Vulkava({
        nodes: [],
        sendWS: (guildId, payload) => {
            client.guilds.cache.get(guildId)?.shard.send(payload);
        }
    });

    client.vulkava.on('queueEnd', async (player) => {
        try {
            player.destroy();
        } catch (err) { }
    });

    client.vulkava.on('error', (node, err) => {
        console.log(chalk.whiteBright('[VULKAVA] ') + chalk.redBright("Error on node ") + chalk.blueBright(node.identifier) + chalk.redBright(" " + err.message));
    });

    client.on('raw', (packet) => client.vulkava.handleVoiceUpdate(packet));`

    play.js: `module.exports = {
    async execute(message, args) {
        let track = args.join(" ");

        const res = await message.client.vulkava.search(track, { source: 'youtubemusic' });

        if (res.loadType === "LOAD_FAILED") {
            return console.log("LOAD_FAILED");
        } else if (res.loadType === "NO_MATCHES") {
            return console.log("NO_MATCHES");
        }

        message.guild.player = message.client.vulkava.createPlayer({
            guildId: message.guild.id,
            voiceChannelId: message.member.voice.channel.id,
            textChannelId: message.channel.id,
            selfDeaf: true
        }); message.guild.player.connect();

        if (res.loadType === 'PLAYLIST_LOADED') {
            for (const track of res.tracks) {
                track.setRequester(message.member);
                message.guild.player.queue.add(track);
            }

            console.log("PLAYLIST LOADED");
        } else {
            const track = res.tracks[0];
            track.setRequester(message.member);

            message.guild.player.queue.add(track);
            console.log("TRACK QUEUED");
        }

        if (!message.guild.player.playing && !message.guild.player.paused) message.guild.player.play();
    }
}`

**Comment by joaopedrosilvestrini** [comment]
Qual musica tá tentando por? Para eu testar aqui

**Comment by Kugyan** [comment]
Ariana Grande – The boy is mine
O problema é q n da nenhuma kkkk

**Comment by joaopedrosilvestrini** [comment]
tenta adicionar o evento error do vulkava, para verificar se não é um erro do node

**Comment by Kugyan** [comment]
😐 No codigo q eu mandei ja tinha o evento: `client.vulkava.on('error', (node, err) => {
    console.log(chalk.whiteBright('[VULKAVA] ') + chalk.redBright("Error on node ") + chalk.blueBright(node.identifier) + chalk.redBright(" " + err.message));
});`

Mas n tem como ser do node, pq tem outro bot no node q funciona, so esta usando um package diferente- 👀

**Comment by davidffa** [comment]
Entre no servidor da lib (https://discord.gg/uT6ePwmPaK), para podermos resolver melhor o problema. Abra lá um post e envie as logs do lavalink.

**Comment by Kugyan** [comment]
https://discord.com/channels/904819972650463262/1226192055387029665
